const STORAGE_KEY="marble-roulette-draw-state-v1";const defaultNames=["김범진 목사님","김민철 목사님","황해성","김용수","김일권","이민철","문성훈","백경훈","이상민","송수엽","송정훈","조기권","이광표","정상훈","김정록","최영환","지성훈","신용진","한기열","박진원","박준형","강인선","장태현","전희진","이효민","이범훈","김태완","심항보","서현우","이영광","박영현","송석리","양원혁","김진광","양찬송","이용현 목사님","김소민","이찬우","김영수","주정환","서현빈 전도사님","배움","윤영섭","김청도"];
const $=s=>document.querySelector(s),canvas=$("#board"),ctx=canvas.getContext("2d");
const el={ready:$("#ready-count"),picked:$("#picked-count"),total:$("#total-count"),winner:$("#winner"),winnerName:$("#winner-name"),start:$("#start"),shuffle:$("#shuffle"),undo:$("#undo"),reset:$("#reset"),share:$("#share"),export:$("#export"),import:$("#import"),file:$("#state-file"),readyEditor:$("#ready-editor"),pickedEditor:$("#picked-editor"),saveReady:$("#save-ready"),savePicked:$("#save-picked"),history:$("#history"),toast:$("#toast")};
let state={ready:[],picked:[],history:[],lastPick:null},balls=[],pegs=[],running=false,raf=0,timer=null;
const colors=["#ffd166","#5eead4","#7dd3fc","#a78bfa","#fb7185","#bef264","#fdba74"];
function parse(t){return t.split("\n").map(x=>x.trim()).filter(Boolean)}
function uniq(a){const s=new Set;return a.filter(x=>{const k=x.toLowerCase();if(s.has(k))return false;s.add(k);return true})}
function normalize(n){const picked=uniq(n.picked||[]),ps=new Set(picked.map(x=>x.toLowerCase())),ready=uniq(n.ready||[]).filter(x=>!ps.has(x.toLowerCase()));state={ready,picked,history:(n.history||[]).filter(Boolean),lastPick:n.lastPick||null}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function enc(){const b=new TextEncoder().encode(JSON.stringify(state));let s="";b.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,'')}
function dec(v){const b=v.replace(/-/g,"+").replace(/_/g,"/"),p=b+"=".repeat((4-b.length%4)%4),bytes=Uint8Array.from(atob(p),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function load(){const h=location.hash.match(/^#state=(.+)$/);if(h){try{normalize(dec(h[1]));save();history.replaceState(null,"",location.pathname+location.search);toast("공유 링크 기록을 불러왔습니다.");return}catch{}}const raw=localStorage.getItem(STORAGE_KEY);if(!raw){normalize({ready:defaultNames,picked:[],history:[]});return}try{normalize(JSON.parse(raw))}catch{normalize({ready:defaultNames,picked:[],history:[]})}}
function toast(m){clearTimeout(timer);el.toast.textContent=m;el.toast.classList.add("show");timer=setTimeout(()=>el.toast.classList.remove("show"),1800)}
function esc(v){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function render(){el.ready.textContent=state.ready.length;el.picked.textContent=state.picked.length;el.total.textContent=state.ready.length+state.picked.length;el.readyEditor.value=state.ready.join("\n");el.pickedEditor.value=state.picked.join("\n");el.winnerName.textContent=state.lastPick||"READY";el.start.disabled=running||!state.ready.length;el.undo.disabled=running||!state.lastPick;el.history.innerHTML=state.history.map((n,i)=>`<li>${i+1}. ${esc(n)}</li>`).join("");drawIdle()}
function makePegs(){pegs=[];for(let y=130;y<560;y+=72){const offset=(Math.floor(y/72)%2)*48;for(let x=120+offset;x<1000;x+=96)pegs.push({x,y,r:10})}}
function makeBalls(){balls=state.ready.map((name,i)=>({name,x:70+(i%22)*44,y:38+Math.floor(i/22)*34,vx:(Math.random()-.5)*2,vy:0,r:13,c:colors[i%colors.length],done:false}))}
function drawBoard(){ctx.clearRect(0,0,1100,720);ctx.fillStyle="#0a1020";ctx.fillRect(0,0,1100,720);ctx.strokeStyle="rgba(255,255,255,.16)";ctx.lineWidth=6;ctx.strokeRect(35,25,1030,650);ctx.fillStyle="rgba(255,209,102,.18)";ctx.fillRect(45,610,1010,12);ctx.fillStyle="#ffd166";ctx.font="900 22px system-ui";ctx.fillText("FINISH",50,598);for(const p of pegs){ctx.beginPath();ctx.fillStyle="rgba(255,255,255,.72)";ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.fillStyle="rgba(255,209,102,.18)";ctx.arc(p.x,p.y,p.r+6,0,Math.PI*2);ctx.fill()}for(const b of balls){ctx.beginPath();ctx.fillStyle=b.c;ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.fillStyle="rgba(255,255,255,.75)";ctx.arc(b.x-5,b.y-5,4,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="900 12px system-ui";ctx.textAlign="center";ctx.fillText(b.name.slice(0,3),b.x,b.y+28)}ctx.textAlign="start"}
function drawIdle(){makePegs();makeBalls();drawBoard()}
function step(){for(const b of balls){if(b.done)continue;b.vy+=.18;b.vx+=Math.sin((b.y+b.x)*.01)*.025;b.x+=b.vx;b.y+=b.vy;if(b.x<48||b.x>1052){b.vx*=-.78;b.x=Math.max(48,Math.min(1052,b.x))}for(const p of pegs){const dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),min=b.r+p.r;if(d<min){const nx=dx/(d||1),ny=dy/(d||1),push=min-d;b.x+=nx*push;b.y+=ny*push;const dot=b.vx*nx+b.vy*ny;b.vx-=1.55*dot*nx;b.vy-=1.55*dot*ny;b.vx+=(Math.random()-.5)*.55}}if(b.y>610){finish(b);return}}drawBoard();raf=requestAnimationFrame(step)}
function start(){if(running||!state.ready.length)return;running=true;el.start.disabled=true;el.winnerName.textContent="RUNNING";makePegs();makeBalls();cancelAnimationFrame(raf);raf=requestAnimationFrame(step)}
function finish(ball){cancelAnimationFrame(raf);running=false;state.ready=state.ready.filter(n=>n!==ball.name);state.picked.push(ball.name);state.history.push(ball.name);state.lastPick=ball.name;save();render();el.winner.classList.remove("pop");void el.winner.offsetWidth;el.winner.classList.add("pop");toast(`${ball.name} 당첨!`)}
function shuffle(){state.ready=state.ready.sort(()=>Math.random()-.5);save();render();toast("출발 순서를 섞었습니다.")}
function undo(){if(!state.lastPick)return;const n=state.lastPick,i=state.picked.lastIndexOf(n);if(i>=0)state.picked.splice(i,1);state.ready.push(n);state.history.pop();state.lastPick=state.history.at(-1)||null;save();render()}
function reset(){normalize({ready:uniq([...state.ready,...state.picked]),picked:[],history:[],lastPick:null});save();render()}
function saveEdit(t){if(t==="ready")normalize({...state,ready:parse(el.readyEditor.value)});else normalize({...state,picked:parse(el.pickedEditor.value)});save();render()}
async function share(){const url=`${location.origin}${location.pathname}#state=${enc()}`;try{await navigator.clipboard.writeText(url);toast("공유 링크를 복사했습니다.")}catch{location.hash=`state=${enc()}`}}
function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="marble-roulette-record.json";a.click();URL.revokeObjectURL(url)}
function importState(f){const r=new FileReader;r.onload=()=>{try{normalize(JSON.parse(String(r.result)));save();render()}catch{toast("파일을 읽지 못했습니다.")}};r.readAsText(f)}
el.start.onclick=start;el.shuffle.onclick=shuffle;el.undo.onclick=undo;el.reset.onclick=reset;el.saveReady.onclick=()=>saveEdit("ready");el.savePicked.onclick=()=>saveEdit("picked");el.share.onclick=share;el.export.onclick=exportState;el.import.onclick=()=>el.file.click();el.file.onchange=()=>{if(el.file.files[0])importState(el.file.files[0]);el.file.value=""};load();render();
